FROM mysql:5.6.38

ENV MYSQL_LFS /Users/miguelhalysortuno/Documents/Master/TFM/devops/docker/mntzcn
ENV MYSQL_ROOT_PASSWORD mysecret
EXPOSE "13306:3306"
VOLUME $MYSQL_LFS/container_data/mysql /var/lib/mysql